Add Mindsensors IR Thermometer sensor
ev3dev/lego-linux-drivers pull request #70
Opened 2018-09-05 01:27 UTC by donei34

2018-09-05 02:12 UTC, dlech requested changes
This looks great!

There are just a few non-obvious things that need to be fixed. See inline comments.

2018-09-05 02:12 UTC, dlech commented on sensors/nxt_i2c_sensor_defs.c
> +		 * @default_address: 0x2A
In linux, the address is shifted to the right one bit compared to RobotC, so the address we need is actually 0x15

Also, 0x15 needs to be added to the list [here](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-stretch/sensors/nxt_i2c_sensor_core.c#L488)

2018-09-05 02:12 UTC, dlech commented on sensors/nxt_i2c_sensor_defs.c
> +	[MS_IR_THERMOMETER] = {
`MS_IR_THERMOMETER` also needs to get added to the lists [here](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-stretch/sensors/nxt_i2c_sensor.h#L129) and [here](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-stretch/sensors/nxt_i2c_sensor.h#L199)

2018-09-05 02:12 UTC, dlech commented on sensors/nxt_i2c_sensor_defs.c
> +		 * @vendor_part_name: IRThermometer
Let's use the same name as on the mindsensors.com website. `IR Temperature Sensor for EV3 or NXT`

2018-09-05 02:12 UTC, dlech commented on sensors/nxt_i2c_sensor_defs.c
> +		.name		= MS_IR_THERMOMETER_NAME,
`MS_IR_THERMOMETER_NAME` needs to be added to the list [here](https://github.com/ev3dev/lego-linux-drivers/blob/ev3dev-stretch/sensors/nxt_i2c_sensor.h#L162)

2018-09-06 02:19 UTC, donei34 commented
I believe that all of your points have been fixed, please let me know if there's anything else I can / need to do!
And thanks for all of your help!!

2018-09-08 16:16 UTC, merged

2018-09-08 16:17 UTC, dlech commented
I've merged it and we will see what happens.