fix: change UART message buffer size to 35 bytes [testing needed]
ev3dev/lego-linux-drivers pull request #79
Opened 2020-08-09 07:56 UTC by JakubVanek

Previously, the buffer was only 34 bytes large. This would overflow the buffer if an INFO message with 32 byte payload was received. The problem is the INFO command byte that is not counted to the payload size.

I haven't tested the change yet, but I will try to do so.

2020-08-09 09:02 UTC, JakubVanek commented
The change compiles and the color sensor works with it on x86_64 laptop, hopefully everything is OK.

2020-08-10 21:13 UTC, dlech reviewed
Nice catch!

2020-08-10 21:13 UTC, dlech commented on sensors/ev3_uart_sensor_ld.c
> +// extra bytes for: main command byte, INFO command byte, final checksum
Could you please change this to `/* */` style comments (it is the Linux kernel style.

2020-08-10 21:16 UTC, dlech requested changes
x

2020-08-10 21:29 UTC, JakubVanek commented
Thanks! I have now changed the style of the comment.

2020-08-10 21:36 UTC, merged